*** Starting uWSGI 2.0.20 (64bit) on [Fri Mar  4 10:55:34 2022] ***
compiled with version: 9.3.0 on 02 March 2022 08:21:41
os: Linux-5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/zun/Python/day06/sanae_note/sanae_note
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/zun/Python/day06/sanae_note
your processes number limit is 15295
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43525 (port auto-assigned) fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ff968b5140
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "sanae_note/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8548)
spawned uWSGI worker 1 (pid: 8549, cores: 1)
spawned uWSGI http 1 (pid: 8550)
